### ISSUE TITLE
重新输入新的Cookie后，报错内容如下

### ISSUE THREAD

**Issue by Duhuan101** [jingming295/bilibili-login#3]
2023-12-23 18:07: [I] loader unload plugin bilibili-login:mx2go5
2023-12-23 18:07: [I] loader apply plugin bilibili-login:mx2go5
2023-12-23 18:07: [I] bilibili-login 第一次登录中，正在初始化。。。
                            at BiliBiliApi.checkNeedRefresh (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-bilibili-login\lib\API\BiliBiliAPI\index.js:28:23)
2023-12-23 18:07: [W] bilibili-login Error: checkNeedRefresh code:-101 message: 账号未登录
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                           at async BilibiliAccount.init (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-bilibili-login\lib\API\BilibiliAccount\index.js:26:29)
                            at async Object.apply (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-bilibili-login\lib\API\index.js:25:13)

配置如下：
![image](https://github.com/jingming295/bilibili-login/assets/152770865/3bcd4124-c401-41af-9c29-1520d670e6ad)

**Comment by Duhuan101** [comment]
but换了一个号就又可以了

**Comment by jingming295** [comment]
这个是被风控了，把那个refresh关掉就可以了
![image](https://github.com/jingming295/bilibili-login/assets/48265334/b228c0a9-0447-43d4-898c-4f8239ada232)

**Comment by jingming295** [comment]
感觉是被风控了，b站经常这样。我的建议是多换几个游览器以无痕模式获取cookie
